"""Default generic memory governance rules."""

from datetime import UTC, datetime

from aion_brain.contracts.memory_governance import MemoryGovernanceRule


def default_memory_governance_rules() -> list[MemoryGovernanceRule]:
    """Return deterministic domain-neutral governance defaults."""
    now = datetime.now(UTC)
    return [
        MemoryGovernanceRule(
            governance_rule_id="memory-governance-deny-restricted-without-scope",
            name="Deny restricted memory without scope",
            description="Restricted memory retrieval requires an explicit restricted scope marker.",
            status="active",
            rule_type="retrieval_gate",
            memory_types=[],
            owner_scope=["workspace:main"],
            sensitivity_levels=["restricted"],
            conditions={
                "sensitivity_in": ["restricted"],
                "metadata_key_equals": {"key": "restricted_scope_present", "value": False},
            },
            action="deny",
            priority=0,
            metadata={"default": True},
            created_by="system",
            created_at=now,
            updated_at=now,
        ),
        MemoryGovernanceRule(
            governance_rule_id="memory-governance-decay-old-low-confidence",
            name="Decay old low confidence memory",
            description="Old low-confidence memory should be decayed instead of treated as fresh.",
            status="active",
            rule_type="decay",
            memory_types=[],
            owner_scope=["workspace:main"],
            sensitivity_levels=[],
            conditions={"confidence_below": 0.35, "age_days_above": 90},
            action="decay",
            priority=20,
            metadata={"default": True},
            created_by="system",
            created_at=now,
            updated_at=now,
        ),
        MemoryGovernanceRule(
            governance_rule_id="memory-governance-approval-for-forget",
            name="Require approval for memory forget",
            description="Forgetting canonical memory requires approval unless already present.",
            status="active",
            rule_type="forgetting",
            memory_types=[],
            owner_scope=["workspace:main"],
            sensitivity_levels=[],
            conditions={"metadata_key_equals": {"key": "approval_present", "value": False}},
            action="require_approval",
            priority=5,
            metadata={"default": True},
            created_by="system",
            created_at=now,
            updated_at=now,
        ),
        MemoryGovernanceRule(
            governance_rule_id="memory-governance-flag-missing-evidence",
            name="Flag memory without evidence reference",
            description="Memory without evidence references should be flagged as recall-only.",
            status="active",
            rule_type="write_gate",
            memory_types=["semantic", "procedural"],
            owner_scope=["workspace:main"],
            sensitivity_levels=[],
            conditions={"evidence_ref_missing": True},
            action="flag_conflict",
            priority=80,
            metadata={"default": True},
            created_by="system",
            created_at=now,
            updated_at=now,
        ),
        MemoryGovernanceRule(
            governance_rule_id="memory-governance-compact-duplicate-semantic",
            name="Compact duplicate semantic memory",
            description="Duplicate semantic memory can be compacted deterministically.",
            status="active",
            rule_type="compaction",
            memory_types=["semantic"],
            owner_scope=["workspace:main"],
            sensitivity_levels=[],
            conditions={"metadata_key_exists": "duplicate_group"},
            action="compact",
            priority=90,
            metadata={"default": True},
            created_by="system",
            created_at=now,
            updated_at=now,
        ),
        MemoryGovernanceRule(
            governance_rule_id="memory-governance-expire-working-memory",
            name="Expire working memory after retention window",
            description="Stale working memory should expire after a generic retention window.",
            status="active",
            rule_type="retention",
            memory_types=["working"],
            owner_scope=["workspace:main"],
            sensitivity_levels=[],
            conditions={"stale_after_days": 7},
            action="expire",
            priority=30,
            metadata={"default": True},
            created_by="system",
            created_at=now,
            updated_at=now,
        ),
        MemoryGovernanceRule(
            governance_rule_id="memory-governance-approval-for-audit-forget",
            name="Require approval for audit memory forget",
            description="Audit memory forgetting requires explicit approval.",
            status="active",
            rule_type="forgetting",
            memory_types=["audit"],
            owner_scope=["workspace:main"],
            sensitivity_levels=[],
            conditions={"metadata_key_equals": {"key": "approval_present", "value": False}},
            action="require_approval",
            priority=1,
            metadata={"default": True},
            created_by="system",
            created_at=now,
            updated_at=now,
        ),
    ]
