"""Create cognitive cycle orchestration tables."""

from __future__ import annotations

from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Index, Integer, MetaData, Table, Text
from sqlalchemy.dialects.postgresql import JSONB

metadata = MetaData()

aion_cognitive_cycle_templates = Table(
    "aion_cognitive_cycle_templates",
    metadata,
    Column("cycle_template_id", Text, primary_key=True),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=False),
    Column("cycle_type", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("owner_scope", JSONB, nullable=False),
    Column("steps", JSONB, nullable=False),
    Column("risk_level", Text, nullable=False),
    Column("requires_approval", Boolean, nullable=False),
    Column("metadata", JSONB, nullable=False),
    Column("created_by", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("disabled_at", DateTime(timezone=True), nullable=True),
    Index("ix_aion_cycle_templates_name", "name"),
    Index("ix_aion_cycle_templates_type", "cycle_type"),
    Index("ix_aion_cycle_templates_status", "status"),
    Index("ix_aion_cycle_templates_risk", "risk_level"),
    Index("ix_aion_cycle_templates_created", "created_at"),
)

aion_cognitive_cycle_runs = Table(
    "aion_cognitive_cycle_runs",
    metadata,
    Column("cycle_run_id", Text, primary_key=True),
    Column("cycle_template_id", Text, nullable=True),
    Column("trace_id", Text, nullable=True),
    Column("actor_id", Text, nullable=True),
    Column("workspace_id", Text, nullable=True),
    Column("cycle_type", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("mode", Text, nullable=False),
    Column("owner_scope", JSONB, nullable=False),
    Column("input", JSONB, nullable=False),
    Column("output", JSONB, nullable=False),
    Column("error", JSONB, nullable=False),
    Column("risk_assessment_id", Text, nullable=True),
    Column("approval_request_id", Text, nullable=True),
    Column("autonomy_decision_id", Text, nullable=True),
    Column("started_at", DateTime(timezone=True), nullable=True),
    Column("completed_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_aion_cycle_runs_template", "cycle_template_id"),
    Index("ix_aion_cycle_runs_trace", "trace_id"),
    Index("ix_aion_cycle_runs_actor", "actor_id"),
    Index("ix_aion_cycle_runs_workspace", "workspace_id"),
    Index("ix_aion_cycle_runs_type", "cycle_type"),
    Index("ix_aion_cycle_runs_status", "status"),
    Index("ix_aion_cycle_runs_mode", "mode"),
    Index("ix_aion_cycle_runs_created", "created_at"),
)

aion_cognitive_cycle_steps = Table(
    "aion_cognitive_cycle_steps",
    metadata,
    Column("cycle_step_run_id", Text, primary_key=True),
    Column(
        "cycle_run_id",
        Text,
        ForeignKey("aion_cognitive_cycle_runs.cycle_run_id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("step_id", Text, nullable=False),
    Column("step_type", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("input", JSONB, nullable=False),
    Column("output", JSONB, nullable=False),
    Column("error", JSONB, nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=True),
    Column("completed_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_aion_cycle_steps_run", "cycle_run_id"),
    Index("ix_aion_cycle_steps_step", "step_id"),
    Index("ix_aion_cycle_steps_type", "step_type"),
    Index("ix_aion_cycle_steps_status", "status"),
    Index("ix_aion_cycle_steps_created", "created_at"),
)

aion_sleep_consolidation_records = Table(
    "aion_sleep_consolidation_records",
    metadata,
    Column("consolidation_id", Text, primary_key=True),
    Column("cycle_run_id", Text, nullable=False),
    Column("trace_id", Text, nullable=True),
    Column("actor_id", Text, nullable=True),
    Column("workspace_id", Text, nullable=True),
    Column("owner_scope", JSONB, nullable=False),
    Column("working_memory_slots_reviewed", Integer, nullable=False),
    Column("memories_decayed", Integer, nullable=False),
    Column("conflicts_detected", Integer, nullable=False),
    Column("compaction_runs", Integer, nullable=False),
    Column("reflections_created", Integer, nullable=False),
    Column("skill_candidates_created", Integer, nullable=False),
    Column("regression_cases_checked", Integer, nullable=False),
    Column("visual_snapshots_created", Integer, nullable=False),
    Column("summary", Text, nullable=False),
    Column("result", JSONB, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Index("ix_aion_sleep_records_run", "cycle_run_id"),
    Index("ix_aion_sleep_records_trace", "trace_id"),
    Index("ix_aion_sleep_records_actor", "actor_id"),
    Index("ix_aion_sleep_records_workspace", "workspace_id"),
    Index("ix_aion_sleep_records_created", "created_at"),
)
