"""Create event reaction router tables."""

from __future__ import annotations

from sqlalchemy import Column, DateTime, ForeignKey, Index, Integer, MetaData, Table, Text
from sqlalchemy.dialects.postgresql import JSONB

metadata = MetaData()

aion_event_subscriptions = Table(
    "aion_event_subscriptions",
    metadata,
    Column("subscription_id", Text, primary_key=True),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("owner_scope", JSONB, nullable=False),
    Column("source_filters", JSONB, nullable=False),
    Column("event_type_patterns", JSONB, nullable=False),
    Column("trigger_rules", JSONB, nullable=False),
    Column("target_type", Text, nullable=False),
    Column("target_id", Text, nullable=True),
    Column("reaction_mode", Text, nullable=False),
    Column("risk_level", Text, nullable=False),
    Column("max_actions", Integer, nullable=False),
    Column("constraints", JSONB, nullable=False),
    Column("metadata", JSONB, nullable=False),
    Column("created_by", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("disabled_at", DateTime(timezone=True), nullable=True),
    Index("ix_aion_event_subscriptions_status", "status"),
    Index("ix_aion_event_subscriptions_target_type", "target_type"),
    Index("ix_aion_event_subscriptions_created_at", "created_at"),
)

aion_event_dispatch_records = Table(
    "aion_event_dispatch_records",
    metadata,
    Column("dispatch_id", Text, primary_key=True),
    Column("event_id", Text, nullable=False),
    Column("trace_id", Text, nullable=True),
    Column("actor_id", Text, nullable=True),
    Column("workspace_id", Text, nullable=True),
    Column("status", Text, nullable=False),
    Column("mode", Text, nullable=False),
    Column("matched_subscription_ids", JSONB, nullable=False),
    Column("actions", JSONB, nullable=False),
    Column("action_count", Integer, nullable=False),
    Column("completed_action_count", Integer, nullable=False),
    Column("failed_action_count", Integer, nullable=False),
    Column("blocked_action_count", Integer, nullable=False),
    Column("result", JSONB, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("completed_at", DateTime(timezone=True), nullable=True),
    Index("ix_aion_event_dispatch_records_event_id", "event_id"),
    Index("ix_aion_event_dispatch_records_trace_id", "trace_id"),
    Index("ix_aion_event_dispatch_records_workspace_id", "workspace_id"),
    Index("ix_aion_event_dispatch_records_status", "status"),
    Index("ix_aion_event_dispatch_records_created_at", "created_at"),
)

aion_event_reaction_actions = Table(
    "aion_event_reaction_actions",
    metadata,
    Column("reaction_action_id", Text, primary_key=True),
    Column(
        "dispatch_id",
        Text,
        ForeignKey("aion_event_dispatch_records.dispatch_id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("subscription_id", Text, nullable=False),
    Column("event_id", Text, nullable=False),
    Column("trace_id", Text, nullable=True),
    Column("target_type", Text, nullable=False),
    Column("target_id", Text, nullable=True),
    Column("action_type", Text, nullable=False),
    Column("mode", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("input", JSONB, nullable=False),
    Column("output", JSONB, nullable=False),
    Column("error", JSONB, nullable=False),
    Column("policy_decision_id", Text, nullable=True),
    Column("risk_assessment_id", Text, nullable=True),
    Column("approval_request_id", Text, nullable=True),
    Column("autonomy_decision_id", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("completed_at", DateTime(timezone=True), nullable=True),
    Index("ix_aion_event_reaction_actions_dispatch_id", "dispatch_id"),
    Index("ix_aion_event_reaction_actions_subscription_id", "subscription_id"),
    Index("ix_aion_event_reaction_actions_event_id", "event_id"),
    Index("ix_aion_event_reaction_actions_trace_id", "trace_id"),
    Index("ix_aion_event_reaction_actions_status", "status"),
    Index("ix_aion_event_reaction_actions_target_type", "target_type"),
    Index("ix_aion_event_reaction_actions_created_at", "created_at"),
)

aion_event_dead_letters = Table(
    "aion_event_dead_letters",
    metadata,
    Column("dead_letter_id", Text, primary_key=True),
    Column("dispatch_id", Text, nullable=False),
    Column("reaction_action_id", Text, nullable=True),
    Column("event_id", Text, nullable=False),
    Column("subscription_id", Text, nullable=True),
    Column("trace_id", Text, nullable=True),
    Column("reason", Text, nullable=False),
    Column("error", JSONB, nullable=False),
    Column("status", Text, nullable=False),
    Column("replay_count", Integer, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("resolved_at", DateTime(timezone=True), nullable=True),
    Index("ix_aion_event_dead_letters_event_id", "event_id"),
    Index("ix_aion_event_dead_letters_subscription_id", "subscription_id"),
    Index("ix_aion_event_dead_letters_trace_id", "trace_id"),
    Index("ix_aion_event_dead_letters_status", "status"),
    Index("ix_aion_event_dead_letters_created_at", "created_at"),
)
