"""Create command bus, idempotency, outbox, inbox, lease, and consistency tables."""

from __future__ import annotations

from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Index, Integer, MetaData, Table, Text
from sqlalchemy import text
from sqlalchemy.dialects.postgresql import JSONB

metadata = MetaData()

aion_commands = Table(
    "aion_commands",
    metadata,
    Column("command_id", Text, primary_key=True),
    Column("trace_id", Text, nullable=True),
    Column("correlation_id", Text, nullable=True),
    Column("idempotency_key", Text, nullable=True),
    Column("actor_id", Text, nullable=True),
    Column("workspace_id", Text, nullable=True),
    Column("command_type", Text, nullable=False),
    Column("target_type", Text, nullable=False),
    Column("target_id", Text, nullable=True),
    Column("mode", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("payload", JSONB, nullable=False),
    Column("result", JSONB, nullable=False),
    Column("error", JSONB, nullable=False),
    Column("policy_decision_id", Text, nullable=True),
    Column("autonomy_decision_id", Text, nullable=True),
    Column("risk_assessment_id", Text, nullable=True),
    Column("approval_request_id", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=True),
    Column("completed_at", DateTime(timezone=True), nullable=True),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_aion_commands_trace_id", "trace_id"),
    Index("ix_aion_commands_correlation_id", "correlation_id"),
    Index("ix_aion_commands_idempotency_key", "idempotency_key"),
    Index("ix_aion_commands_actor_id", "actor_id"),
    Index("ix_aion_commands_workspace_id", "workspace_id"),
    Index("ix_aion_commands_command_type", "command_type"),
    Index("ix_aion_commands_target_type", "target_type"),
    Index("ix_aion_commands_mode", "mode"),
    Index("ix_aion_commands_status", "status"),
    Index("ix_aion_commands_created_at", "created_at"),
    Index(
        "uq_aion_commands_idempotency_key_not_null",
        "idempotency_key",
        unique=True,
        postgresql_where=text("idempotency_key IS NOT NULL"),
    ),
)

aion_idempotency_records = Table(
    "aion_idempotency_records",
    metadata,
    Column("idempotency_key", Text, primary_key=True),
    Column("actor_id", Text, nullable=True),
    Column("workspace_id", Text, nullable=True),
    Column("route", Text, nullable=False),
    Column("request_hash", Text, nullable=False),
    Column("response_hash", Text, nullable=True),
    Column("status", Text, nullable=False),
    Column("response", JSONB, nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_aion_idempotency_records_actor_id", "actor_id"),
    Index("ix_aion_idempotency_records_workspace_id", "workspace_id"),
    Index("ix_aion_idempotency_records_route", "route"),
    Index("ix_aion_idempotency_records_request_hash", "request_hash"),
    Index("ix_aion_idempotency_records_status", "status"),
    Index("ix_aion_idempotency_records_expires_at", "expires_at"),
    Index("ix_aion_idempotency_records_created_at", "created_at"),
)

aion_outbox_messages = Table(
    "aion_outbox_messages",
    metadata,
    Column("outbox_id", Text, primary_key=True),
    Column("trace_id", Text, nullable=True),
    Column("correlation_id", Text, nullable=True),
    Column("message_type", Text, nullable=False),
    Column("destination", Text, nullable=False),
    Column("subject", Text, nullable=True),
    Column("payload", JSONB, nullable=False),
    Column("headers", JSONB, nullable=False),
    Column("status", Text, nullable=False),
    Column("attempt_count", Integer, nullable=False),
    Column("max_attempts", Integer, nullable=False),
    Column("next_attempt_at", DateTime(timezone=True), nullable=True),
    Column("last_error", JSONB, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("sent_at", DateTime(timezone=True), nullable=True),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_aion_outbox_messages_trace_id", "trace_id"),
    Index("ix_aion_outbox_messages_correlation_id", "correlation_id"),
    Index("ix_aion_outbox_messages_message_type", "message_type"),
    Index("ix_aion_outbox_messages_destination", "destination"),
    Index("ix_aion_outbox_messages_subject", "subject"),
    Index("ix_aion_outbox_messages_status", "status"),
    Index("ix_aion_outbox_messages_next_attempt_at", "next_attempt_at"),
    Index("ix_aion_outbox_messages_created_at", "created_at"),
)

aion_outbox_delivery_attempts = Table(
    "aion_outbox_delivery_attempts",
    metadata,
    Column("delivery_attempt_id", Text, primary_key=True),
    Column(
        "outbox_id",
        Text,
        ForeignKey("aion_outbox_messages.outbox_id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("status", Text, nullable=False),
    Column("attempt_number", Integer, nullable=False),
    Column("error", JSONB, nullable=False),
    Column("latency_ms", Integer, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Index("ix_aion_outbox_delivery_attempts_outbox_id", "outbox_id"),
    Index("ix_aion_outbox_delivery_attempts_status", "status"),
    Index("ix_aion_outbox_delivery_attempts_attempt_number", "attempt_number"),
    Index("ix_aion_outbox_delivery_attempts_created_at", "created_at"),
)

aion_inbox_messages = Table(
    "aion_inbox_messages",
    metadata,
    Column("inbox_id", Text, primary_key=True),
    Column("source", Text, nullable=False),
    Column("external_message_id", Text, nullable=False),
    Column("trace_id", Text, nullable=True),
    Column("correlation_id", Text, nullable=True),
    Column("message_type", Text, nullable=False),
    Column("payload_hash", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("processed_by", Text, nullable=True),
    Column("result", JSONB, nullable=False),
    Column("error", JSONB, nullable=False),
    Column("received_at", DateTime(timezone=True), nullable=False),
    Column("processed_at", DateTime(timezone=True), nullable=True),
    Index("ix_aion_inbox_messages_source", "source"),
    Index("ix_aion_inbox_messages_external_message_id", "external_message_id"),
    Index("ix_aion_inbox_messages_trace_id", "trace_id"),
    Index("ix_aion_inbox_messages_correlation_id", "correlation_id"),
    Index("ix_aion_inbox_messages_message_type", "message_type"),
    Index("ix_aion_inbox_messages_status", "status"),
    Index("ix_aion_inbox_messages_received_at", "received_at"),
    Index("uq_aion_inbox_source_external_message_id", "source", "external_message_id", unique=True),
)

aion_processing_leases = Table(
    "aion_processing_leases",
    metadata,
    Column("lease_id", Text, primary_key=True),
    Column("resource_type", Text, nullable=False),
    Column("resource_id", Text, nullable=False),
    Column("owner_id", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("metadata", JSONB, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("released_at", DateTime(timezone=True), nullable=True),
    Index("ix_aion_processing_leases_resource_type", "resource_type"),
    Index("ix_aion_processing_leases_resource_id", "resource_id"),
    Index("ix_aion_processing_leases_owner_id", "owner_id"),
    Index("ix_aion_processing_leases_status", "status"),
    Index("ix_aion_processing_leases_expires_at", "expires_at"),
    Index("ix_aion_processing_leases_created_at", "created_at"),
    Index(
        "uq_aion_processing_leases_active_resource",
        "resource_type",
        "resource_id",
        "status",
        unique=True,
        postgresql_where=text("status = 'active'"),
    ),
)

aion_consistency_checks = Table(
    "aion_consistency_checks",
    metadata,
    Column("consistency_check_id", Text, primary_key=True),
    Column("trace_id", Text, nullable=True),
    Column("check_type", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("scope", JSONB, nullable=False),
    Column("violations", JSONB, nullable=False),
    Column("repaired", Boolean, nullable=False),
    Column("result", JSONB, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("completed_at", DateTime(timezone=True), nullable=True),
    Index("ix_aion_consistency_checks_trace_id", "trace_id"),
    Index("ix_aion_consistency_checks_check_type", "check_type"),
    Index("ix_aion_consistency_checks_status", "status"),
    Index("ix_aion_consistency_checks_repaired", "repaired"),
    Index("ix_aion_consistency_checks_created_at", "created_at"),
)
