"""Create sandbox, secret reference, connector, and runtime permission tables."""

from __future__ import annotations

from sqlalchemy import Boolean, Column, DateTime, Float, Index, MetaData, Table, Text
from sqlalchemy.dialects.postgresql import JSONB

metadata = MetaData()

aion_sandbox_profiles = Table(
    "aion_sandbox_profiles",
    metadata,
    Column("sandbox_profile_id", Text, primary_key=True),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("sandbox_type", Text, nullable=False),
    Column("owner_scope", JSONB, nullable=False),
    Column("resource_limits", JSONB, nullable=False),
    Column("egress_rules", JSONB, nullable=False),
    Column("filesystem_rules", JSONB, nullable=False),
    Column("allowed_runtime_permissions", JSONB, nullable=False),
    Column("secret_refs_allowed", JSONB, nullable=False),
    Column("connector_refs_allowed", JSONB, nullable=False),
    Column("network_enabled", Boolean, nullable=False),
    Column("filesystem_write_enabled", Boolean, nullable=False),
    Column("process_spawn_enabled", Boolean, nullable=False),
    Column("metadata", JSONB, nullable=False),
    Column("created_by", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("disabled_at", DateTime(timezone=True), nullable=True),
    Index("ix_aion_sandbox_profiles_name", "name"),
    Index("ix_aion_sandbox_profiles_status", "status"),
    Index("ix_aion_sandbox_profiles_sandbox_type", "sandbox_type"),
    Index("ix_aion_sandbox_profiles_network_enabled", "network_enabled"),
    Index("ix_aion_sandbox_profiles_process_spawn_enabled", "process_spawn_enabled"),
    Index("ix_aion_sandbox_profiles_created_at", "created_at"),
)

aion_secret_refs = Table(
    "aion_secret_refs",
    metadata,
    Column("secret_ref_id", Text, primary_key=True),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("owner_scope", JSONB, nullable=False),
    Column("secret_type", Text, nullable=False),
    Column("provider", Text, nullable=False),
    Column("external_ref", Text, nullable=True),
    Column("sensitivity", Text, nullable=False),
    Column("rotation_policy", JSONB, nullable=False),
    Column("metadata", JSONB, nullable=False),
    Column("created_by", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("disabled_at", DateTime(timezone=True), nullable=True),
    Column("last_rotated_at", DateTime(timezone=True), nullable=True),
    Index("ix_aion_secret_refs_name", "name"),
    Index("ix_aion_secret_refs_status", "status"),
    Index("ix_aion_secret_refs_secret_type", "secret_type"),
    Index("ix_aion_secret_refs_provider", "provider"),
    Index("ix_aion_secret_refs_sensitivity", "sensitivity"),
    Index("ix_aion_secret_refs_created_at", "created_at"),
)

aion_connector_definitions = Table(
    "aion_connector_definitions",
    metadata,
    Column("connector_id", Text, primary_key=True),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("connector_type", Text, nullable=False),
    Column("owner_scope", JSONB, nullable=False),
    Column("base_endpoint_ref", Text, nullable=True),
    Column("auth_secret_ref_id", Text, nullable=True),
    Column("allowed_actions", JSONB, nullable=False),
    Column("allowed_scopes", JSONB, nullable=False),
    Column("risk_level", Text, nullable=False),
    Column("metadata", JSONB, nullable=False),
    Column("created_by", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("disabled_at", DateTime(timezone=True), nullable=True),
    Index("ix_aion_connector_definitions_name", "name"),
    Index("ix_aion_connector_definitions_status", "status"),
    Index("ix_aion_connector_definitions_connector_type", "connector_type"),
    Index("ix_aion_connector_definitions_auth_secret_ref_id", "auth_secret_ref_id"),
    Index("ix_aion_connector_definitions_risk_level", "risk_level"),
    Index("ix_aion_connector_definitions_created_at", "created_at"),
)

aion_runtime_permission_grants = Table(
    "aion_runtime_permission_grants",
    metadata,
    Column("runtime_permission_id", Text, primary_key=True),
    Column("target_type", Text, nullable=False),
    Column("target_id", Text, nullable=False),
    Column("sandbox_profile_id", Text, nullable=True),
    Column("owner_scope", JSONB, nullable=False),
    Column("permissions", JSONB, nullable=False),
    Column("secret_refs", JSONB, nullable=False),
    Column("connector_refs", JSONB, nullable=False),
    Column("status", Text, nullable=False),
    Column("granted_by", Text, nullable=True),
    Column("expires_at", DateTime(timezone=True), nullable=True),
    Column("metadata", JSONB, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("revoked_at", DateTime(timezone=True), nullable=True),
    Index("ix_aion_runtime_permission_grants_target_type", "target_type"),
    Index("ix_aion_runtime_permission_grants_target_id", "target_id"),
    Index("ix_aion_runtime_permission_grants_sandbox_profile_id", "sandbox_profile_id"),
    Index("ix_aion_runtime_permission_grants_status", "status"),
    Index("ix_aion_runtime_permission_grants_expires_at", "expires_at"),
    Index("ix_aion_runtime_permission_grants_created_at", "created_at"),
)

aion_sandbox_validation_records = Table(
    "aion_sandbox_validation_records",
    metadata,
    Column("validation_id", Text, primary_key=True),
    Column("sandbox_profile_id", Text, nullable=True),
    Column("target_type", Text, nullable=False),
    Column("target_id", Text, nullable=True),
    Column("status", Text, nullable=False),
    Column("score", Float, nullable=False),
    Column("checks", JSONB, nullable=False),
    Column("failures", JSONB, nullable=False),
    Column("warnings", JSONB, nullable=False),
    Column("metadata", JSONB, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Index("ix_aion_sandbox_validation_records_sandbox_profile_id", "sandbox_profile_id"),
    Index("ix_aion_sandbox_validation_records_target_type", "target_type"),
    Index("ix_aion_sandbox_validation_records_target_id", "target_id"),
    Index("ix_aion_sandbox_validation_records_status", "status"),
    Index("ix_aion_sandbox_validation_records_score", "score"),
    Index("ix_aion_sandbox_validation_records_created_at", "created_at"),
)

aion_sandbox_runs = Table(
    "aion_sandbox_runs",
    metadata,
    Column("sandbox_run_id", Text, primary_key=True),
    Column("trace_id", Text, nullable=True),
    Column("actor_id", Text, nullable=True),
    Column("workspace_id", Text, nullable=True),
    Column("sandbox_profile_id", Text, nullable=False),
    Column("target_type", Text, nullable=False),
    Column("target_id", Text, nullable=True),
    Column("mode", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("input", JSONB, nullable=False),
    Column("output", JSONB, nullable=False),
    Column("error", JSONB, nullable=False),
    Column("risk_assessment_id", Text, nullable=True),
    Column("approval_request_id", Text, nullable=True),
    Column("autonomy_decision_id", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=True),
    Column("completed_at", DateTime(timezone=True), nullable=True),
    Index("ix_aion_sandbox_runs_trace_id", "trace_id"),
    Index("ix_aion_sandbox_runs_actor_id", "actor_id"),
    Index("ix_aion_sandbox_runs_workspace_id", "workspace_id"),
    Index("ix_aion_sandbox_runs_sandbox_profile_id", "sandbox_profile_id"),
    Index("ix_aion_sandbox_runs_target_type", "target_type"),
    Index("ix_aion_sandbox_runs_target_id", "target_id"),
    Index("ix_aion_sandbox_runs_mode", "mode"),
    Index("ix_aion_sandbox_runs_status", "status"),
    Index("ix_aion_sandbox_runs_created_at", "created_at"),
)
