"""Create policy catalog, permission matrix, and test harness tables."""

from __future__ import annotations

from sqlalchemy import Column, DateTime, Index, Integer, MetaData, Table, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB

metadata = MetaData()

aion_policy_action_catalog = Table(
    "aion_policy_action_catalog",
    metadata,
    Column("policy_action_id", Text, primary_key=True),
    Column("action_type", Text, nullable=False),
    Column("category", Text, nullable=False),
    Column("resource_type", Text, nullable=False),
    Column("default_risk_level", Text, nullable=False),
    Column("required_permission", Text, nullable=False),
    Column("description", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("metadata", JSONB, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("disabled_at", DateTime(timezone=True), nullable=True),
    UniqueConstraint("action_type", name="uq_aion_policy_action_catalog_action_type"),
    Index("ix_aion_policy_action_catalog_action_type", "action_type"),
    Index("ix_aion_policy_action_catalog_category", "category"),
    Index("ix_aion_policy_action_catalog_resource_type", "resource_type"),
    Index("ix_aion_policy_action_catalog_default_risk_level", "default_risk_level"),
    Index("ix_aion_policy_action_catalog_required_permission", "required_permission"),
    Index("ix_aion_policy_action_catalog_status", "status"),
    Index("ix_aion_policy_action_catalog_created_at", "created_at"),
)

aion_permission_catalog = Table(
    "aion_permission_catalog",
    metadata,
    Column("permission_id", Text, primary_key=True),
    Column("permission", Text, nullable=False),
    Column("category", Text, nullable=False),
    Column("resource_type", Text, nullable=False),
    Column("action_pattern", Text, nullable=False),
    Column("description", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("metadata", JSONB, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("disabled_at", DateTime(timezone=True), nullable=True),
    UniqueConstraint("permission", name="uq_aion_permission_catalog_permission"),
    Index("ix_aion_permission_catalog_permission", "permission"),
    Index("ix_aion_permission_catalog_category", "category"),
    Index("ix_aion_permission_catalog_resource_type", "resource_type"),
    Index("ix_aion_permission_catalog_action_pattern", "action_pattern"),
    Index("ix_aion_permission_catalog_status", "status"),
    Index("ix_aion_permission_catalog_created_at", "created_at"),
)

aion_role_templates = Table(
    "aion_role_templates",
    metadata,
    Column("role_template_id", Text, primary_key=True),
    Column("role_name", Text, nullable=False),
    Column("description", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("permissions", JSONB, nullable=False),
    Column("constraints", JSONB, nullable=False),
    Column("metadata", JSONB, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("disabled_at", DateTime(timezone=True), nullable=True),
    UniqueConstraint("role_name", name="uq_aion_role_templates_role_name"),
    Index("ix_aion_role_templates_role_name", "role_name"),
    Index("ix_aion_role_templates_status", "status"),
    Index("ix_aion_role_templates_created_at", "created_at"),
)

aion_policy_simulations = Table(
    "aion_policy_simulations",
    metadata,
    Column("simulation_id", Text, primary_key=True),
    Column("trace_id", Text, nullable=True),
    Column("actor_id", Text, nullable=True),
    Column("workspace_id", Text, nullable=True),
    Column("action_type", Text, nullable=False),
    Column("resource_type", Text, nullable=False),
    Column("resource_id", Text, nullable=True),
    Column("input", JSONB, nullable=False),
    Column("decision", JSONB, nullable=False),
    Column("explanation", JSONB, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Index("ix_aion_policy_simulations_trace_id", "trace_id"),
    Index("ix_aion_policy_simulations_actor_id", "actor_id"),
    Index("ix_aion_policy_simulations_workspace_id", "workspace_id"),
    Index("ix_aion_policy_simulations_action_type", "action_type"),
    Index("ix_aion_policy_simulations_resource_type", "resource_type"),
    Index("ix_aion_policy_simulations_created_at", "created_at"),
)

aion_policy_test_cases = Table(
    "aion_policy_test_cases",
    metadata,
    Column("policy_test_case_id", Text, primary_key=True),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("action_type", Text, nullable=False),
    Column("resource_type", Text, nullable=False),
    Column("input", JSONB, nullable=False),
    Column("expected", JSONB, nullable=False),
    Column("tags", JSONB, nullable=False),
    Column("metadata", JSONB, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("disabled_at", DateTime(timezone=True), nullable=True),
    Index("ix_aion_policy_test_cases_name", "name"),
    Index("ix_aion_policy_test_cases_status", "status"),
    Index("ix_aion_policy_test_cases_action_type", "action_type"),
    Index("ix_aion_policy_test_cases_resource_type", "resource_type"),
    Index("ix_aion_policy_test_cases_created_at", "created_at"),
)

aion_policy_test_runs = Table(
    "aion_policy_test_runs",
    metadata,
    Column("policy_test_run_id", Text, primary_key=True),
    Column("status", Text, nullable=False),
    Column("total_count", Integer, nullable=False),
    Column("passed_count", Integer, nullable=False),
    Column("failed_count", Integer, nullable=False),
    Column("warning_count", Integer, nullable=False),
    Column("results", JSONB, nullable=False),
    Column("report", JSONB, nullable=False),
    Column("created_by", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("completed_at", DateTime(timezone=True), nullable=True),
    Index("ix_aion_policy_test_runs_status", "status"),
    Index("ix_aion_policy_test_runs_created_at", "created_at"),
)

aion_policy_bundle_records = Table(
    "aion_policy_bundle_records",
    metadata,
    Column("policy_bundle_id", Text, primary_key=True),
    Column("bundle_type", Text, nullable=False),
    Column("version", Text, nullable=False),
    Column("content_hash", Text, nullable=False),
    Column("content", JSONB, nullable=False),
    Column("status", Text, nullable=False),
    Column("created_by", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Index("ix_aion_policy_bundle_records_bundle_type", "bundle_type"),
    Index("ix_aion_policy_bundle_records_version", "version"),
    Index("ix_aion_policy_bundle_records_content_hash", "content_hash"),
    Index("ix_aion_policy_bundle_records_status", "status"),
    Index("ix_aion_policy_bundle_records_created_at", "created_at"),
)
