"""Governed self-improvement control-plane services."""

from aion_brain.self_improvement.approval import bind_human_approval
from aion_brain.self_improvement.benchmark_contracts import (
    EVALUATION_AUTHORIZATION_SCOPE,
    EVALUATION_AUTHORIZATION_TRANSACTION_ID,
    EVALUATION_IMPLEMENTATION_TASK,
    REQUIRED_BENCHMARK_METRICS,
    BenchmarkBaseline,
    BenchmarkCandidateResult,
    BenchmarkCaseReference,
    BenchmarkComparison,
    BenchmarkDriftReport,
    BenchmarkEvaluationBundle,
    BenchmarkManifest,
    BenchmarkMetric,
    BenchmarkMetricDelta,
    BenchmarkSafetyGate,
)
from aion_brain.self_improvement.benchmark_registry import BenchmarkRegistry
from aion_brain.self_improvement.benchmark_runner import (
    build_evaluation_bundle,
    run_candidate_benchmark,
)
from aion_brain.self_improvement.canary import CanaryController
from aion_brain.self_improvement.canary_contracts import (
    CANARY_AUTHORIZATION_SCOPE,
    CANARY_AUTHORIZATION_TRANSACTION_ID,
    CANARY_IMPLEMENTATION_TASK,
    CANARY_RUNTIME_ENABLED,
    PRODUCTION_EXPOSURE_ENABLED,
    ROLLBACK_TRIGGERS,
    CanaryApprovalBinding,
    CanaryDecision,
    CanaryExposureBudget,
    CanaryMetricThreshold,
    CanaryObservation,
    CanaryPlan,
    ImprovementOutcome,
    RollbackDecision,
)
from aion_brain.self_improvement.case_based_planner import (
    AdaptedPlan,
    CaseBasedPlanner,
    PlanningCase,
)
from aion_brain.self_improvement.change_budget import evaluate_change_budget
from aion_brain.self_improvement.ci_monitor import (
    CheckStatus,
    CICheckResult,
    CIMonitor,
    CIMonitorAdapter,
    CIReport,
    DeterministicTestCIMonitorAdapter,
    DisabledCIMonitorAdapter,
)
from aion_brain.self_improvement.comparison import compare_baseline_to_candidate
from aion_brain.self_improvement.diff_hash import (
    DiffHashEvidence,
    candidate_commit_fingerprint,
    canonical_diff_hash,
    canonical_json_hash,
    changed_paths_fingerprint,
    normalize_diff,
    sha256_text,
)
from aion_brain.self_improvement.evaluation_evidence import (
    benchmark_metrics_from_evaluator_records,
    capture_evaluation_provenance,
)
from aion_brain.self_improvement.evidence import redact_evidence_payload
from aion_brain.self_improvement.experiment import (
    ApprovalTier,
    ImprovementEvidenceBundle,
    ImprovementExperimentPlan,
    ImprovementExperimentResult,
    ImprovementProposal,
    ProposalLifecycleState,
    approval_tier_for_risk,
)
from aion_brain.self_improvement.experiment_runner import (
    DeterministicExperimentCandidateProvider,
    DisabledExperimentCandidateProvider,
    ExperimentCandidateProvider,
    ImprovementExperimentRunner,
)
from aion_brain.self_improvement.git_controller import (
    GitController,
    GitSnapshot,
    TaskBranchRequest,
)
from aion_brain.self_improvement.governance import evaluate_governance
from aion_brain.self_improvement.holdout import (
    assert_holdout_controls,
    patch_generator_case_ids,
)
from aion_brain.self_improvement.hypothesis import (
    DeterministicTestHypothesisGenerator,
    DisabledHypothesisGenerator,
    HypothesisGenerator,
    ImprovementChangeType,
    ImprovementHypothesis,
    MetricDirection,
)
from aion_brain.self_improvement.integrated_pipeline import (
    IntegratedDryRunResult,
    IntegratedSelfImprovementDryRun,
)
from aion_brain.self_improvement.ledger import SelfImprovementLedger
from aion_brain.self_improvement.lifecycle import (
    can_transition,
    require_valid_transition,
    transition_state,
)
from aion_brain.self_improvement.merge_controller import (
    DeterministicTestMergeAdapter,
    DisabledMergeAdapter,
    MergeAdapter,
    MergeController,
    MergeRequest,
    MergeResult,
    MergeStatus,
)
from aion_brain.self_improvement.monitoring import (
    CanaryMonitor,
    CanaryMonitoringSummary,
    required_rollback_triggers,
)
from aion_brain.self_improvement.observation import (
    EXPERIMENT_AUTHORIZATION_SCOPE,
    EXPERIMENT_AUTHORIZATION_TRANSACTION_ID,
    EXPERIMENT_IMPLEMENTATION_TASK,
    ImprovementObservation,
    ObservationSourceType,
    observation_from_evaluation_record,
)
from aion_brain.self_improvement.outcome_ledger import (
    ImprovementOutcomeLedger,
    LearningLedgerRecord,
)
from aion_brain.self_improvement.patch_generator import (
    DeterministicTestPatchGenerator,
    DisabledPatchGenerator,
    PatchArtifact,
    PatchGenerator,
    PatchRequest,
)
from aion_brain.self_improvement.patch_validator import (
    ChangeObservation,
    PatchValidationResult,
    PatchValidator,
    PathPolicy,
    TestWeakeningReport,
    analyze_test_weakening,
)
from aion_brain.self_improvement.pattern_intake import (
    ImprovementFailurePattern,
    ImprovementFailurePatternType,
    intake_failure_pattern,
)
from aion_brain.self_improvement.pr_controller import (
    ApprovalStatus,
    DeterministicTestPullRequestAdapter,
    DisabledPullRequestAdapter,
    PullRequestAdapter,
    PullRequestController,
    PullRequestCreateRequest,
    PullRequestRecord,
    RewriteApprovalBinding,
)
from aion_brain.self_improvement.preference_learning import (
    PreferenceDistribution,
    PreferenceLearner,
    UserPreferenceSignal,
)
from aion_brain.self_improvement.proposal_service import ImprovementProposalService
from aion_brain.self_improvement.protected_paths import (
    protected_path_decision,
    protected_path_decisions,
    touches_protected_core,
)
from aion_brain.self_improvement.regression_proposal import (
    DeterministicTestRegressionProposalGenerator,
    DisabledRegressionTestProposalGenerator,
    RegressionTestProposal,
    RegressionTestProposalGenerator,
)
from aion_brain.self_improvement.retrieval_optimizer import (
    RetrievalRankingOptimizer,
    RetrievalRankingStatus,
    RetrievalRankingVersion,
)
from aion_brain.self_improvement.risk import assess_improvement_risk
from aion_brain.self_improvement.rollback import (
    RollbackMetadata,
    rollback_metadata_for_candidate,
)
from aion_brain.self_improvement.rollback_controller import RollbackController
from aion_brain.self_improvement.sandbox import (
    REQUIRED_SANDBOX_GATES,
    DeterministicTestSandboxRunner,
    DisabledSandboxRunner,
    SandboxCommand,
    SandboxCommandResult,
    SandboxGateName,
    SandboxRunEvidence,
    SandboxRunner,
    build_sandbox_evidence,
    required_sandbox_commands,
)
from aion_brain.self_improvement.skill_evolution import (
    ProceduralSkillEvolution,
    ProceduralSkillRecord,
)
from aion_brain.self_improvement.strategy_selector import (
    ContextBucketStrategySelector,
    StrategySelection,
    StrategySelectionPolicy,
    StrategyStats,
)
from aion_brain.self_improvement.test_first import (
    RegressionTestSpec,
    TestCommandResult,
    TestFirstEvidence,
    TestFirstVerifier,
)
from aion_brain.self_improvement.worktree import (
    REWRITE_AUTHORIZATION_SCOPE,
    REWRITE_AUTHORIZATION_TRANSACTION_ID,
    REWRITE_IMPLEMENTATION_TASK,
    DisabledGitCommandRunner,
    GitCommandRunner,
    WorktreeManager,
    WorktreeRequest,
    WorktreeResult,
)

__all__ = [
    "EVALUATION_AUTHORIZATION_SCOPE",
    "EVALUATION_AUTHORIZATION_TRANSACTION_ID",
    "EVALUATION_IMPLEMENTATION_TASK",
    "EXPERIMENT_AUTHORIZATION_SCOPE",
    "EXPERIMENT_AUTHORIZATION_TRANSACTION_ID",
    "EXPERIMENT_IMPLEMENTATION_TASK",
    "REQUIRED_BENCHMARK_METRICS",
    "REQUIRED_SANDBOX_GATES",
    "REWRITE_AUTHORIZATION_SCOPE",
    "REWRITE_AUTHORIZATION_TRANSACTION_ID",
    "REWRITE_IMPLEMENTATION_TASK",
    "ROLLBACK_TRIGGERS",
    "CANARY_AUTHORIZATION_SCOPE",
    "CANARY_AUTHORIZATION_TRANSACTION_ID",
    "CANARY_IMPLEMENTATION_TASK",
    "CANARY_RUNTIME_ENABLED",
    "PRODUCTION_EXPOSURE_ENABLED",
    "AdaptedPlan",
    "ApprovalStatus",
    "ApprovalTier",
    "BenchmarkBaseline",
    "BenchmarkCandidateResult",
    "BenchmarkCaseReference",
    "BenchmarkComparison",
    "BenchmarkDriftReport",
    "BenchmarkEvaluationBundle",
    "BenchmarkManifest",
    "BenchmarkMetric",
    "BenchmarkMetricDelta",
    "BenchmarkRegistry",
    "BenchmarkSafetyGate",
    "CICheckResult",
    "CIMonitor",
    "CIMonitorAdapter",
    "CIReport",
    "CanaryApprovalBinding",
    "CanaryController",
    "CanaryDecision",
    "CanaryExposureBudget",
    "CanaryMetricThreshold",
    "CanaryMonitor",
    "CanaryMonitoringSummary",
    "CanaryObservation",
    "CanaryPlan",
    "CaseBasedPlanner",
    "ChangeObservation",
    "CheckStatus",
    "ContextBucketStrategySelector",
    "DeterministicExperimentCandidateProvider",
    "DeterministicTestCIMonitorAdapter",
    "DeterministicTestHypothesisGenerator",
    "DeterministicTestMergeAdapter",
    "DeterministicTestPatchGenerator",
    "DeterministicTestPullRequestAdapter",
    "DeterministicTestRegressionProposalGenerator",
    "DeterministicTestSandboxRunner",
    "DiffHashEvidence",
    "DisabledCIMonitorAdapter",
    "DisabledExperimentCandidateProvider",
    "DisabledGitCommandRunner",
    "DisabledHypothesisGenerator",
    "DisabledMergeAdapter",
    "DisabledPatchGenerator",
    "DisabledPullRequestAdapter",
    "DisabledRegressionTestProposalGenerator",
    "DisabledSandboxRunner",
    "ExperimentCandidateProvider",
    "GitController",
    "GitCommandRunner",
    "GitSnapshot",
    "HypothesisGenerator",
    "ImprovementChangeType",
    "ImprovementEvidenceBundle",
    "ImprovementExperimentPlan",
    "ImprovementExperimentResult",
    "ImprovementFailurePattern",
    "ImprovementFailurePatternType",
    "ImprovementHypothesis",
    "ImprovementObservation",
    "ImprovementOutcome",
    "ImprovementOutcomeLedger",
    "ImprovementProposal",
    "ImprovementProposalService",
    "ImprovementExperimentRunner",
    "IntegratedDryRunResult",
    "IntegratedSelfImprovementDryRun",
    "LearningLedgerRecord",
    "MetricDirection",
    "MergeAdapter",
    "MergeController",
    "MergeRequest",
    "MergeResult",
    "MergeStatus",
    "ObservationSourceType",
    "PatchArtifact",
    "PatchGenerator",
    "PatchRequest",
    "PatchValidationResult",
    "PatchValidator",
    "PathPolicy",
    "PlanningCase",
    "PreferenceDistribution",
    "PreferenceLearner",
    "UserPreferenceSignal",
    "ProceduralSkillEvolution",
    "ProceduralSkillRecord",
    "ProposalLifecycleState",
    "PullRequestAdapter",
    "PullRequestController",
    "PullRequestCreateRequest",
    "PullRequestRecord",
    "RegressionTestProposal",
    "RegressionTestProposalGenerator",
    "RegressionTestSpec",
    "RetrievalRankingOptimizer",
    "RetrievalRankingStatus",
    "RetrievalRankingVersion",
    "RewriteApprovalBinding",
    "RollbackMetadata",
    "RollbackController",
    "RollbackDecision",
    "SandboxCommand",
    "SandboxCommandResult",
    "SandboxGateName",
    "SandboxRunEvidence",
    "SandboxRunner",
    "SelfImprovementLedger",
    "StrategySelection",
    "StrategySelectionPolicy",
    "StrategyStats",
    "TaskBranchRequest",
    "TestCommandResult",
    "TestFirstEvidence",
    "TestFirstVerifier",
    "TestWeakeningReport",
    "WorktreeManager",
    "WorktreeRequest",
    "WorktreeResult",
    "analyze_test_weakening",
    "approval_tier_for_risk",
    "assess_improvement_risk",
    "assert_holdout_controls",
    "benchmark_metrics_from_evaluator_records",
    "bind_human_approval",
    "can_transition",
    "build_sandbox_evidence",
    "build_evaluation_bundle",
    "candidate_commit_fingerprint",
    "capture_evaluation_provenance",
    "canonical_diff_hash",
    "canonical_json_hash",
    "changed_paths_fingerprint",
    "compare_baseline_to_candidate",
    "evaluate_change_budget",
    "evaluate_governance",
    "intake_failure_pattern",
    "normalize_diff",
    "observation_from_evaluation_record",
    "patch_generator_case_ids",
    "protected_path_decision",
    "protected_path_decisions",
    "redact_evidence_payload",
    "require_valid_transition",
    "required_rollback_triggers",
    "required_sandbox_commands",
    "rollback_metadata_for_candidate",
    "run_candidate_benchmark",
    "sha256_text",
    "touches_protected_core",
    "transition_state",
]
