"""Default generic guardrail rules."""

from datetime import UTC, datetime

from aion_brain.contracts.guardrails import GuardrailRule


def default_guardrail_rules() -> list[GuardrailRule]:
    """Return deterministic domain-neutral default guardrails."""
    now = datetime.now(UTC)
    return [
        GuardrailRule(
            guardrail_id="guardrail-critical-risk-block",
            name="Critical risk block",
            description="Critical generic actions are blocked unless overridden by policy later.",
            status="active",
            scope=["workspace:main"],
            action_types=["*"],
            resource_types=["*"],
            risk_levels=["critical"],
            conditions={},
            effect="block",
            severity="critical",
            metadata={"default": True},
            created_by="system",
            created_at=now,
            updated_at=now,
            disabled_at=None,
        ),
        GuardrailRule(
            guardrail_id="guardrail-controlled-execution-approval",
            name="Controlled execution approval",
            description=(
                "Controlled generic execution requires approval when no approval is present."
            ),
            status="active",
            scope=["workspace:main"],
            action_types=["*"],
            resource_types=["*"],
            risk_levels=["medium", "high", "critical"],
            conditions={"mode": "controlled", "approval_present": False},
            effect="require_approval",
            severity="high",
            metadata={"default": True},
            created_by="system",
            created_at=now,
            updated_at=now,
            disabled_at=None,
        ),
        GuardrailRule(
            guardrail_id="guardrail-external-effect-approval",
            name="External effect approval",
            description="Generic external effects require approval.",
            status="active",
            scope=["workspace:main"],
            action_types=["*"],
            resource_types=["*"],
            risk_levels=["low", "medium", "high", "critical"],
            conditions={"external_effect_possible": True, "approval_present": False},
            effect="require_approval",
            severity="high",
            metadata={"default": True},
            created_by="system",
            created_at=now,
            updated_at=now,
            disabled_at=None,
        ),
        GuardrailRule(
            guardrail_id="guardrail-delete-data-block",
            name="Data deletion block",
            description="Generic data deletion is blocked without an approval signal.",
            status="active",
            scope=["workspace:main"],
            action_types=["*"],
            resource_types=["*"],
            risk_levels=["medium", "high", "critical"],
            conditions={"deletes_data": True, "approval_present": False},
            effect="block",
            severity="critical",
            metadata={"default": True},
            created_by="system",
            created_at=now,
            updated_at=now,
            disabled_at=None,
        ),
        GuardrailRule(
            guardrail_id="guardrail-secret-payload-block",
            name="Secret-like payload block",
            description="Payloads marked as secret-like are blocked at the guardrail boundary.",
            status="active",
            scope=["workspace:main"],
            action_types=["*"],
            resource_types=["*"],
            risk_levels=["low", "medium", "high", "critical"],
            conditions={"secret_like_payload_detected": True},
            effect="block",
            severity="critical",
            metadata={"default": True},
            created_by="system",
            created_at=now,
            updated_at=now,
            disabled_at=None,
        ),
        GuardrailRule(
            guardrail_id="guardrail-external-model-approval",
            name="External model approval",
            description="External model use requires approval when requested by generic context.",
            status="active",
            scope=["workspace:main"],
            action_types=["*"],
            resource_types=["*"],
            risk_levels=["medium", "high", "critical"],
            conditions={"uses_external_model": True, "approval_present": False},
            effect="require_approval",
            severity="high",
            metadata={"default": True},
            created_by="system",
            created_at=now,
            updated_at=now,
            disabled_at=None,
        ),
        GuardrailRule(
            guardrail_id="guardrail-mcp-approval",
            name="MCP approval",
            description="MCP-backed controlled calls require approval.",
            status="active",
            scope=["workspace:main"],
            action_types=["*"],
            resource_types=["*"],
            risk_levels=["medium", "high", "critical"],
            conditions={"uses_mcp": True, "approval_present": False},
            effect="require_approval",
            severity="high",
            metadata={"default": True},
            created_by="system",
            created_at=now,
            updated_at=now,
            disabled_at=None,
        ),
        GuardrailRule(
            guardrail_id="guardrail-skill-activation-approval",
            name="Skill activation approval",
            description=(
                "Skill activation and promotion effects require approval for elevated risk."
            ),
            status="active",
            scope=["workspace:main"],
            action_types=["*"],
            resource_types=["*"],
            risk_levels=["high", "critical"],
            conditions={"affects_skill_activation": True, "approval_present": False},
            effect="require_approval",
            severity="high",
            metadata={"default": True},
            created_by="system",
            created_at=now,
            updated_at=now,
            disabled_at=None,
        ),
    ]
